#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Download the raw daily series that feed the Central Highlands (Tay Nguyen)
Irrigation / Water Availability Index, one file per station.

Source: NASA POWER daily point API (free, no key, MERRA-2 / GEOS land surface).
  PRECTOTCORR  corrected precipitation                       mm/day
  GWETTOP      surface soil wetness      (0-5 cm)            0-1
  GWETROOT     root-zone soil wetness    (~0-100 cm)         0-1
  GWETPROF     profile soil wetness      (whole column)      0-1
  T2M / T2M_MAX / T2M_MIN  air temperature                   degC   (Hargreaves PET)

This script only DOWNLOADS and stores the series. Every index (rainfall
anomalies, soil-moisture percentiles, the groundwater-reservoir model, the
composite WAI) is computed in assets/wai.js so the browser and this snapshot
can never disagree on the maths.

Output:
  data/water/manifest.js       window.CH_WATER_MANIFEST
  data/water/<station>.js      window.CH_WATER["<station>"]

Run:
  python build_water_index.py            # all stations
  python build_water_index.py pleiku     # one station
"""
import os, sys, json, time, urllib.request
from datetime import date, timedelta

HERE = os.path.dirname(os.path.abspath(__file__))
OUTDIR = os.path.join(HERE, "data", "water")

# Approximate town centroids, 5 provinces of the Central Highlands.
# (id, name, province, lat, lon, altitude m, weight = rough share of national
#  robusta area carried by that point; normalised in the page.)
STATIONS = [
    ("buon_ma_thuot", "Buon Ma Thuot", "Dak Lak",   12.6667, 108.0500, 536, 0.10),
    ("cu_mgar",       "Cu M'gar",      "Dak Lak",   12.9000, 108.0333, 500, 0.10),
    ("ea_hleo",       "Ea H'leo",      "Dak Lak",   13.2333, 108.2167, 600, 0.10),
    ("dak_mil",       "Dak Mil",       "Dak Nong",  12.4500, 107.6167, 700, 0.12),
    ("gia_nghia",     "Gia Nghia",     "Dak Nong",  11.9833, 107.6917, 600, 0.12),
    ("pleiku",        "Pleiku",        "Gia Lai",   13.9833, 108.0000, 750, 0.06),
    ("chu_se",        "Chu Se",        "Gia Lai",   13.6833, 108.0833, 700, 0.06),
    ("dak_ha",        "Dak Ha",        "Kon Tum",   14.5333, 107.9500, 570, 0.03),
    ("di_linh",       "Di Linh",       "Lam Dong",  11.5833, 108.0667, 950, 0.125),
    ("bao_loc",       "Bao Loc",       "Lam Dong",  11.5500, 107.8083, 850, 0.125),
]

START = "19910101"          # 1991-2020 WMO normal = the index baseline
FILL = -999.0
PARAMS = ["PRECTOTCORR", "GWETTOP", "GWETROOT", "GWETPROF", "T2M", "T2M_MAX", "T2M_MIN"]
KEYS = ["p", "gt", "gr", "gp", "t", "tx", "tn"]
DEC = {"p": 1, "gt": 3, "gr": 3, "gp": 3, "t": 1, "tx": 1, "tn": 1}


def end_date():
    """POWER publishes with a few days of latency."""
    return (date.today() - timedelta(days=4)).strftime("%Y%m%d")


def fetch(lat, lon, start, end, tries=4):
    url = ("https://power.larc.nasa.gov/api/temporal/daily/point"
           f"?parameters={','.join(PARAMS)}&community=AG"
           f"&latitude={lat}&longitude={lon}&start={start}&end={end}&format=JSON")
    last = None
    for k in range(tries):
        try:
            with urllib.request.urlopen(url, timeout=300) as r:
                return json.load(r)["properties"]["parameter"]
        except Exception as e:                      # noqa: BLE001
            last = e
            time.sleep(5 * (k + 1))
    raise RuntimeError(f"NASA POWER fetch failed for {lat},{lon}: {last!r}")


def build_station(st, end):
    sid, name, prov, lat, lon, alt, w = st
    par = fetch(lat, lon, START, end)
    days = sorted(par[PARAMS[0]].keys())
    if days[0] != START:
        print(f"  ! {sid}: series starts {days[0]}", flush=True)
    out = {}
    for key, p in zip(KEYS, PARAMS):
        src = par[p]
        col = []
        for d in days:
            v = src.get(d)
            col.append(None if v is None or v <= FILL else round(v, DEC[key]))
        out[key] = col
    miss = sum(1 for v in out["p"] if v is None)
    print(f"  {sid}: {len(days)} days {days[0]}..{days[-1]}, {miss} gaps", flush=True)
    return {
        "id": sid, "name": name, "province": prov,
        "lat": lat, "lon": lon, "alt": alt, "weight": w,
        "start": days[0], "end": days[-1], "n": len(days), "vars": out,
    }


def write_js(path, varname, payload, note):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(f"// AUTO-GENERATED by build_water_index.py — {note}. Do not edit by hand.\n")
        f.write(varname + " = ")
        json.dump(payload, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")


def main():
    only = set(sys.argv[1:])
    end = end_date()
    todo = [s for s in STATIONS if not only or s[0] in only]
    if only and not todo:
        sys.exit(f"unknown station(s): {', '.join(sorted(only))}")
    print(f"NASA POWER window: {START} -> {end}", flush=True)
    done = []
    for st in todo:
        print(f"  fetching {st[1]} ({st[3]},{st[4]}) ...", flush=True)
        data = build_station(st, end)
        write_js(os.path.join(OUTDIR, f"{st[0]}.js"),
                 f'window.CH_WATER=window.CH_WATER||{{}};window.CH_WATER["{st[0]}"]',
                 data, "NASA POWER daily point")
        done.append(data)
        time.sleep(1.0)

    # Manifest keeps whatever stations already exist on disk when only some were rebuilt.
    stations = [{k: d[k] for k in
                 ("id", "name", "province", "lat", "lon", "alt", "weight", "start", "end", "n")}
                for d in done]
    have = {s["id"] for s in stations}
    mpath = os.path.join(OUTDIR, "manifest.js")
    if only and os.path.exists(mpath):
        txt = open(mpath, encoding="utf-8").read()
        old = json.loads(txt[txt.index("=") + 1:txt.rstrip().rstrip(";").rindex("}") + 1])
        stations += [s for s in old.get("stations", []) if s["id"] not in have]
        stations.sort(key=lambda s: [t[0] for t in STATIONS].index(s["id"]))
    write_js(mpath, "window.CH_WATER_MANIFEST", {
        "generated": date.today().strftime("%Y-%m-%d"),
        "baseline": "1991-2020",
        "source": "NASA POWER daily point (PRECTOTCORR, GWETTOP, GWETROOT, GWETPROF, T2M/MAX/MIN)",
        "stations": stations,
    }, "station manifest")
    print(f"wrote {len(done)} station file(s) + manifest in {OUTDIR}", flush=True)


if __name__ == "__main__":
    main()
